name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

permissions:
  contents: write
  pages: write      # Ye zaroori hai
  id-token: write   # Ye bhi zaroori hai

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter build web --release --base-href /my_portfolio/
      - name: Upload production-ready build artifacts
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./build/web

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
